//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaProductos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IN04
    {
        public int CodigoProducto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> SaldoInventario { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string UsuarioIngreso { get; set; }
        public Nullable<int> IDFamilia { get; set; }
    
        public virtual IN05 IN05 { get; set; }
    }
}
