USE [master]
GO
/****** Object:  Database [PruebaTec2]    Script Date: 10/3/2022 12:42:52 ******/
CREATE DATABASE [PruebaTec2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PruebaTec2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PruebaTec2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PruebaTec2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PruebaTec2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PruebaTec2] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PruebaTec2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PruebaTec2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PruebaTec2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PruebaTec2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PruebaTec2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PruebaTec2] SET ARITHABORT OFF 
GO
ALTER DATABASE [PruebaTec2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PruebaTec2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PruebaTec2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PruebaTec2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PruebaTec2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PruebaTec2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PruebaTec2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PruebaTec2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PruebaTec2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PruebaTec2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PruebaTec2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PruebaTec2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PruebaTec2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PruebaTec2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PruebaTec2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PruebaTec2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PruebaTec2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PruebaTec2] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PruebaTec2] SET  MULTI_USER 
GO
ALTER DATABASE [PruebaTec2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PruebaTec2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PruebaTec2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PruebaTec2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PruebaTec2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PruebaTec2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PruebaTec2] SET QUERY_STORE = OFF
GO
USE [PruebaTec2]
GO
/****** Object:  Table [dbo].[IN04]    Script Date: 10/3/2022 12:42:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IN04](
	[CodigoProducto] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [varchar](50) NULL,
	[Precio] [decimal](18, 2) NULL,
	[SaldoInventario] [decimal](18, 2) NULL,
	[FechaIngreso] [datetime] NULL,
	[UsuarioIngreso] [varchar](50) NULL,
	[IDFamilia] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CodigoProducto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IN05]    Script Date: 10/3/2022 12:42:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IN05](
	[IDFamilia] [int] IDENTITY(1,1) NOT NULL,
	[NombreFamilia] [varchar](50) NULL,
	[UsuarioIngreso] [varchar](50) NULL,
	[Estado] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[IDFamilia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[IN04] ON 
GO
INSERT [dbo].[IN04] ([CodigoProducto], [Descripcion], [Precio], [SaldoInventario], [FechaIngreso], [UsuarioIngreso], [IDFamilia]) VALUES (1, N'Cama king', CAST(500000.00 AS Decimal(18, 2)), CAST(1000000.00 AS Decimal(18, 2)), CAST(N'2021-10-14T00:00:00.000' AS DateTime), N'Jose', NULL)
GO
INSERT [dbo].[IN04] ([CodigoProducto], [Descripcion], [Precio], [SaldoInventario], [FechaIngreso], [UsuarioIngreso], [IDFamilia]) VALUES (2, N'Sillon', CAST(100000.00 AS Decimal(18, 2)), CAST(500000.00 AS Decimal(18, 2)), CAST(N'2022-01-05T00:00:00.000' AS DateTime), N'Jose', NULL)
GO
SET IDENTITY_INSERT [dbo].[IN04] OFF
GO
SET IDENTITY_INSERT [dbo].[IN05] ON 
GO
INSERT [dbo].[IN05] ([IDFamilia], [NombreFamilia], [UsuarioIngreso], [Estado]) VALUES (1, N'Jiron', N'Jose', 1)
GO
SET IDENTITY_INSERT [dbo].[IN05] OFF
GO
ALTER TABLE [dbo].[IN04]  WITH CHECK ADD  CONSTRAINT [fk_grupo] FOREIGN KEY([IDFamilia])
REFERENCES [dbo].[IN05] ([IDFamilia])
GO
ALTER TABLE [dbo].[IN04] CHECK CONSTRAINT [fk_grupo]
GO
USE [master]
GO
ALTER DATABASE [PruebaTec2] SET  READ_WRITE 
GO
